from enum import Enum

class Permission(Enum): 
    """
        The different permissions for a space

    Args:
        Enum (_type_): _description_
    """
    VIEWSPACE_PERMISSION = "VIEWSPACE_PERMISSION"
    REMOVE_OWN_CONTENT_PERMISSION = "REMOVE_OWN_CONTENT_PERMISSION"
    CREATEEDIT_PAGE_PERMISSION = "CREATEEDIT_PAGE_PERMISSION"
    REMOVE_PAGE_PERMISSION = "REMOVE_PAGE_PERMISSION"
    EDITBLOG_PERMISSION = "EDITBLOG_PERMISSION"
    REMOVE_BLOG_PERMISSION = "REMOVE_BLOG_PERMISSION"
    CREATE_ATTACHMENT_PERMISSION = "CREATE_ATTACHMENT_PERMISSION"
    REMOVE_ATTACHMENT_PERMISSION = "REMOVE_ATTACHMENT_PERMISSION"
    COMMENT_PERMISSION = "COMMENT_PERMISSION"
    REMOVE_COMMENT_PERMISSION = "REMOVE_COMMENT_PERMISSION"
    SET_PAGE_PERMISSIONS_PERMISSION = "SET_PAGE_PERMISSIONS_PERMISSION"
    REMOVE_MAIL_PERMISSION = "REMOVE_MAIL_PERMISSION"
    EXPORT_SPACE_PERMISSION = "EXPORT_SPACE_PERMISSION"
    ADMINISTER_SPACE_PERMISSION = "ADMINISTER_SPACE_PERMISSION"